/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./../src/components/AppHeader.vue')['default']
    ComponentsButton: typeof import('./../src/components/Components/ComponentsButton.vue')['default']
    ComponentsDialog: typeof import('./../src/components/Components/ComponentsDialog.vue')['default']
    ComponentsForm: typeof import('./../src/components/Components/ComponentsForm.vue')['default']
    ComponentsNotification: typeof import('./../src/components/Components/ComponentsNotification.vue')['default']
    ComponentsOther: typeof import('./../src/components/Components/ComponentsOther.vue')['default']
    ComponentsTab: typeof import('./../src/components/Home/ComponentsTab.vue')['default']
    CustomDialog: typeof import('./../src/components/Components/Dialog/CustomDialog.vue')['default']
    CustomIcon: typeof import('./../src/components/Components/Other/CustomIcon.vue')['default']
    DefaultCheckbox: typeof import('./../src/components/Components/Form/DefaultCheckbox.vue')['default']
    DefaultDialog: typeof import('./../src/components/Components/Dialog/DefaultDialog.vue')['default']
    DefaultIcon: typeof import('./../src/components/Components/Other/DefaultIcon.vue')['default']
    DefaultInput: typeof import('./../src/components/Components/Form/DefaultInput.vue')['default']
    DefaultRadio: typeof import('./../src/components/Components/Form/DefaultRadio.vue')['default']
    DefaultSelect: typeof import('./../src/components/Components/Form/DefaultSelect.vue')['default']
    DefaultSkeleton: typeof import('./../src/components/Components/Other/DefaultSkeleton.vue')['default']
    DefaultTooltip: typeof import('./../src/components/Components/Other/DefaultTooltip.vue')['default']
    DropdownButton: typeof import('./../src/components/Components/Button/DropdownButton.vue')['default']
    ExpansionItem: typeof import('./../src/components/Components/Other/ExpansionItem.vue')['default']
    GroupButton: typeof import('./../src/components/Components/Button/GroupButton.vue')['default']
    HomeMain: typeof import('./../src/components/Home/HomeMain.vue')['default']
    IAppLandscape: typeof import('~icons/app/landscape')['default']
    OptionsSelect: typeof import('./../src/components/Components/Form/OptionsSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesTab: typeof import('./../src/components/Home/RoutesTab.vue')['default']
    SingleButton: typeof import('./../src/components/Components/Button/SingleButton.vue')['default']
    ToggleButton: typeof import('./../src/components/Components/Button/ToggleButton.vue')['default']
  }
}
